// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lamtndlnezdgdviqqjgx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhbXRuZGxuZXpkZ2R2aXFxamd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1Nzg5OTcsImV4cCI6MjA3MTE1NDk5N30.J7bKmOZBa-A-v8B2kWl5GqWZD_pY_m4efuKseHiZgio";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});